### ISSUE TITLE
Translate Japanese terms to English ones?

### ISSUE THREAD

**Issue by ongtw** [hasseily/Deathlord-Relorded#10]
Thanks for this repo, will give Deathlord a spin!

Just wondering if it is feasible to translate the Japanese terms in the game into English ones, e.g. class names, weapons, etc, just to make the game a little easier and quicker to play, without having to remap terms mentally.

**Comment by MylesWow** [comment]
Seconded! Most japanese words in this game are direct translations anyway. Neru = to sleep (verb), Nigeru = to run (verb), Mahoutsukai = magic user (noun). I would not be surprised if most of the japanese words in this game came from a dictionary off the shelf of a public library when the developers had to change everything on short notice.

**Comment by hasseily** [comment]
Sorry for the (very) late response. It's well known that the devs just picked up almost random words from the dictionary and shoved them in the game at the last moment to switch the setting from Norse to Japanese.
Yes, it's feasible to translate the Japanese terms. However, more works needs to be done to intercept the written text (especially in the magic selection menu) to rewrite it in English.

**Comment by hasseily** [comment]
1.0.7 has support for switching to english for classes, races and items.
Spells haven't been translated.
